### PR TITLE
Gitpod config

### PR DESCRIPTION
**Pull request by astrojuanlu**
- Changed some filenames and tests
- Improved instructions
- Added setup commands where appropriate

Closes https://github.com/kedro-org/kedro-devrel/issues/35.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Trying to preinstall mamba on the images, to no avail 🤔 left a question here https://stackoverflow.com/q/75695521/554319 going to ask on their Discord community too.

**Comment by astrojuanlu** [comment]
I got recommended on Discord to use a custom Docker image like stated here https://www.gitpod.io/docs/introduction/languages/python#python-versions

**Review by noklam — APPROVED** [review]
Everything works for me! Is `mamba` kind of a drop-in replacement for `conda`?

**Comment by astrojuanlu** [comment]
> Is mamba kind of a drop-in replacement for conda?

It is, and it's a delight to use ✨ 

For completeness, conda lately is shipping with a new solver based on mamba called `libmamba` that accelerates things a bit. But I still find mamba and micromamba much more lightweight, the progress indicators much nicer, and in general the performance is still better.

**Pull request merged**
